name = "Banana Farm"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe94f8d6d5e1b7a06019f043de506a483bccd53ac86261335b82ffb58f930cf"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
