name = "Banana Farm"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3126bdb474d44895596f0fc6f4a0fd4601dbe2ce8f2c7c1af5c8e44f391dc719"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
