name = "Banana Farm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aa9fbdf747c3fffb9a802e2eda457d178a1bbc82399d27a67ac7ca487707932"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
